var searchData=
[
  ['os_5fcore_2ec_262',['os_core.c',['../os__core_8c.html',1,'']]],
  ['os_5fcore_2eh_263',['os_core.h',['../os__core_8h.html',1,'']]],
  ['os_5finput_2ec_264',['os_input.c',['../os__input_8c.html',1,'']]],
  ['os_5finput_2eh_265',['os_input.h',['../os__input_8h.html',1,'']]],
  ['os_5fmem_5fdrivers_2ec_266',['os_mem_drivers.c',['../os__mem__drivers_8c.html',1,'']]],
  ['os_5fmem_5fdrivers_2eh_267',['os_mem_drivers.h',['../os__mem__drivers_8h.html',1,'']]],
  ['os_5fmemheap_5fdrivers_2ec_268',['os_memheap_drivers.c',['../os__memheap__drivers_8c.html',1,'']]],
  ['os_5fmemheap_5fdrivers_2eh_269',['os_memheap_drivers.h',['../os__memheap__drivers_8h.html',1,'']]],
  ['os_5fmemory_2ec_270',['os_memory.c',['../os__memory_8c.html',1,'']]],
  ['os_5fmemory_2eh_271',['os_memory.h',['../os__memory_8h.html',1,'']]],
  ['os_5fmemory_5fstrategies_2ec_272',['os_memory_strategies.c',['../os__memory__strategies_8c.html',1,'']]],
  ['os_5fmemory_5fstrategies_2eh_273',['os_memory_strategies.h',['../os__memory__strategies_8h.html',1,'']]],
  ['os_5fprocess_2eh_274',['os_process.h',['../os__process_8h.html',1,'']]],
  ['os_5fscheduler_2ec_275',['os_scheduler.c',['../os__scheduler_8c.html',1,'']]],
  ['os_5fscheduler_2eh_276',['os_scheduler.h',['../os__scheduler_8h.html',1,'']]],
  ['os_5fscheduling_5fstrategies_2ec_277',['os_scheduling_strategies.c',['../os__scheduling__strategies_8c.html',1,'']]],
  ['os_5fscheduling_5fstrategies_2eh_278',['os_scheduling_strategies.h',['../os__scheduling__strategies_8h.html',1,'']]],
  ['os_5ftaskman_2eh_279',['os_taskman.h',['../os__taskman_8h.html',1,'']]],
  ['os_5fuser_5fprivileges_2eh_280',['os_user_privileges.h',['../os__user__privileges_8h.html',1,'']]]
];
